// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Persion.proto

package com.grpcpk;

public final class Persion {
  private Persion() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_grpcpk_StreamRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_grpcpk_StreamRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_grpcpk_StreamResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_grpcpk_StreamResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_grpcpk_StudentResponseList_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_grpcpk_StudentResponseList_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_grpcpk_StudentResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_grpcpk_StudentResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_grpcpk_StudentRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_grpcpk_StudentRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_grpcpk_MyRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_grpcpk_MyRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_grpcpk_MyResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_grpcpk_MyResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\rPersion.proto\022\ncom.grpcpk\"\"\n\rStreamReq" +
      "uest\022\021\n\trequestId\030\001 \001(\t\"$\n\016StreamRespons" +
      "e\022\022\n\nresponseId\030\001 \001(\t\"K\n\023StudentResponse" +
      "List\0224\n\017studentResponse\030\001 \003(\0132\033.com.grpc" +
      "pk.StudentResponse\"F\n\017StudentResponse\022\n\n" +
      "\002id\030\001 \001(\t\022\014\n\004name\030\002 \001(\t\022\013\n\003age\030\003 \001(\t\022\014\n\004" +
      "home\030\004 \001(\t\"\034\n\016StudentRequest\022\n\n\002id\030\001 \001(\t" +
      "\"\035\n\tMyRequest\022\020\n\010username\030\001 \001(\t\"\036\n\nMyRes" +
      "ponse\022\020\n\010realname\030\001 \001(\t2\270\002\n\016StudentServi" +
      "ce\022>\n\013GetUserName\022\025.com.grpcpk.MyRequest" +
      "\032\026.com.grpcpk.MyResponse\"\000\022I\n\nGetStuById" +
      "\022\032.com.grpcpk.StudentRequest\032\033.com.grpcp" +
      "k.StudentResponse\"\0000\001\022L\n\016GetStudnetList\022" +
      "\025.com.grpcpk.MyRequest\032\037.com.grpcpk.Stud" +
      "entResponseList\"\000(\001\022M\n\016StreamInfoById\022\031." +
      "com.grpcpk.StreamRequest\032\032.com.grpcpk.St" +
      "reamResponse\"\000(\0010\001B\027\n\ncom.grpcpkB\007Persio" +
      "nP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_com_grpcpk_StreamRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_grpcpk_StreamRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_grpcpk_StreamRequest_descriptor,
        new String[] { "RequestId", });
    internal_static_com_grpcpk_StreamResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_grpcpk_StreamResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_grpcpk_StreamResponse_descriptor,
        new String[] { "ResponseId", });
    internal_static_com_grpcpk_StudentResponseList_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_com_grpcpk_StudentResponseList_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_grpcpk_StudentResponseList_descriptor,
        new String[] { "StudentResponse", });
    internal_static_com_grpcpk_StudentResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_com_grpcpk_StudentResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_grpcpk_StudentResponse_descriptor,
        new String[] { "Id", "Name", "Age", "Home", });
    internal_static_com_grpcpk_StudentRequest_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_com_grpcpk_StudentRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_grpcpk_StudentRequest_descriptor,
        new String[] { "Id", });
    internal_static_com_grpcpk_MyRequest_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_com_grpcpk_MyRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_grpcpk_MyRequest_descriptor,
        new String[] { "Username", });
    internal_static_com_grpcpk_MyResponse_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_com_grpcpk_MyResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_grpcpk_MyResponse_descriptor,
        new String[] { "Realname", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
