// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Persion.proto

package com.grpcpk;

public interface StreamRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.grpcpk.StreamRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string requestId = 1;</code>
   * @return The requestId.
   */
  String getRequestId();
  /**
   * <code>string requestId = 1;</code>
   * @return The bytes for requestId.
   */
  com.google.protobuf.ByteString
      getRequestIdBytes();
}
