// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Persion.proto

package com.grpcpk;

public interface StreamResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.grpcpk.StreamResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string responseId = 1;</code>
   * @return The responseId.
   */
  String getResponseId();
  /**
   * <code>string responseId = 1;</code>
   * @return The bytes for responseId.
   */
  com.google.protobuf.ByteString
      getResponseIdBytes();
}
