// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Persion.proto

package com.grpcpk;

public interface StudentResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.grpcpk.StudentResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string id = 1;</code>
   * @return The id.
   */
  String getId();
  /**
   * <code>string id = 1;</code>
   * @return The bytes for id.
   */
  com.google.protobuf.ByteString
      getIdBytes();

  /**
   * <code>string name = 2;</code>
   * @return The name.
   */
  String getName();
  /**
   * <code>string name = 2;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>string age = 3;</code>
   * @return The age.
   */
  String getAge();
  /**
   * <code>string age = 3;</code>
   * @return The bytes for age.
   */
  com.google.protobuf.ByteString
      getAgeBytes();

  /**
   * <code>string home = 4;</code>
   * @return The home.
   */
  String getHome();
  /**
   * <code>string home = 4;</code>
   * @return The bytes for home.
   */
  com.google.protobuf.ByteString
      getHomeBytes();
}
