// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Persion.proto

package com.grpcpk;

public interface StudentRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.grpcpk.StudentRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string id = 1;</code>
   * @return The id.
   */
  String getId();
  /**
   * <code>string id = 1;</code>
   * @return The bytes for id.
   */
  com.google.protobuf.ByteString
      getIdBytes();
}
